# Generated by Django 5.2 on 2025-05-31 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACCOUNT_BALANCE', models.IntegerField()),
                ('ACCOUNT_HOLDER', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TASK_TITLE', models.CharField(max_length=100)),
                ('TASK_CREATED_ON', models.DateField(auto_now_add=True, null=True)),
                ('TASK_DUE_DATE', models.DateField()),
                ('TASK_REWARD', models.IntegerField()),
                ('TASK_CLOSED_ON', models.DateField(null=True)),
                ('TASK_DESCRIPTION', models.CharField(max_length=300)),
                ('TASK_HOLDER', models.CharField(max_length=100, null=True)),
                ('TASK_STATUS', models.CharField(choices=[('Open', 'Open'), ('In-process', 'In-process'), ('Reopened', 'Reopened'), ('Closed', 'Closed'), ('Expired', 'Expired'), ('Resolved', 'Resolved')], default='Open', max_length=100)),
                ('TASK_CLOSED_BY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CLOSED_BY', to=settings.AUTH_USER_MODEL)),
                ('TASK_CREATED_BY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CREATED_BY', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.taskdetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
