# Generated by Django 5.2 on 2025-05-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdetail',
            old_name='TASK_CLOSED_BY',
            new_name='TASK_CLOSED',
        ),
        migrations.RenameField(
            model_name='taskdetail',
            old_name='TASK_CREATED_BY',
            new_name='TASK_CREATED',
        ),
    ]
