# Generated by Django 5.2 on 2025-04-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TASK_TITLE', models.CharField(max_length=100)),
                ('TASK_CREATED_BY', models.CharField(max_length=100)),
                ('TASK_CLOSED_BY', models.CharField(max_length=100)),
                ('TASK_CREATED_ON', models.DateField()),
                ('TASK_DUE_DATE', models.DateField()),
                ('TASK_REWARD', models.IntegerField()),
                ('TASK_CLOSED_ON', models.DateField()),
                ('TASK_DESCRIPTION', models.CharField(max_length=300)),
                ('TASK_HOLDER', models.CharField(max_length=100)),
                ('TASK_STATUS', models.CharField(max_length=100)),
            ],
        ),
    ]
