# Generated by Django 5.2 on 2025-06-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0002_rename_task_closed_by_taskdetail_task_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetail',
            name='TASK_DEPARTMENT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
