# Generated by Django 5.2 on 2025-04-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_taskdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDetails',
            new_name='TaskDetail',
        ),
    ]
