# Generated by Django 5.2 on 2025-04-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_taskdetails_taskdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_CREATED_ON',
            field=models.DateField(null=True),
        ),
    ]
