# Generated by Django 5.2 on 2025-04-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_taskdetail_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_CLOSED_BY',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_CREATED_BY',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_DUE_DATE',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_HOLDER',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
