# Generated by Django 5.2 on 2025-04-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_taskdetail_task_closed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_CLOSED_ON',
            field=models.DateField(null=True),
        ),
    ]
