# Generated by Django 5.2 on 2025-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_taskdetail_task_closed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_DUE_DATE',
            field=models.DateField(),
        ),
    ]
