# Generated by Django 5.2 on 2025-04-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_taskdetail_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_CREATED_ON',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
