# Generated by Django 5.2 on 2025-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_taskdetail_task_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_STATUS',
            field=models.CharField(choices=[('Open', 'Open'), ('ReOpen', 'ReOpen'), ('Closed', 'Closed'), ('Expired', 'Expired'), ('Resolved', 'Resolved')], default='Open', max_length=100),
        ),
    ]
