# Generated by Django 5.2 on 2025-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_taskdetail_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_STATUS',
            field=models.CharField(choices=[('Open', 'Open'), ('In-process', 'In-process'), ('ReOpen', 'ReOpen'), ('Closed', 'Closed'), ('Expired', 'Expired'), ('Resolved', 'Resolved')], default='Open', max_length=100),
        ),
    ]
