# Generated by Django 5.2 on 2025-05-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_mycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='TASK_STATUS',
            field=models.CharField(choices=[('Open', 'Open'), ('In-process', 'In-process'), ('Reopened', 'Reopened'), ('Closed', 'Closed'), ('Expired', 'Expired'), ('Resolved', 'Resolved')], default='Open', max_length=100),
        ),
    ]
