# Generated by Django 5.2 on 2025-05-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
