# Generated by Django 5.2 on 2025-05-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_userprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Department',
        ),
    ]
